import React from 'react'
import { Fragment } from 'react'
import Head from 'next/head'

const About = () => {
  return (
      <div>
<Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>About Page</div>
        <p>lorem ipsum</p>
      </div>
  )
}

export default About