// const https = require('https');
// const httpsAgent = new https.Agent({
//     rejectUnauthorized: false,
//   });

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState,useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home({courses}) {
  const {data}=courses;
  console.log(courses)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href="/about">About</Link>
        <Link href="/blog">Blog</Link>
        <section id='courses'>
          <div className='row'>
            {data?.map(course=>(
              <div key={course.courseId} className='col-lg-4'>
                  <Image loader={() => course.photoUrl} src={course.photoUrl} 
                    alt={course.courseName} width={400} height={200}
                    quality={100}
                    />
                  <h4>
                    <Link href={`/course/${course.courseId}`}>
                      <a>{course.courseName}</a>
                    </Link>
                    </h4>
              </div>
            ))}
          </div>

        </section>
      </main>
    </div>
  )
}

export async function getStaticProps(){
  const response= await fetch("http://elxanquliyev2-001-site3.htempurl.com/api/course")
  const data=await response.json()
  return {
    props:{
    courses:{data},
  }}
}
